### Added by Zplugin's installer
source ~/.zplugin/bin/zplugin.zsh
autoload -Uz _zplugin
(( ${+_comps} )) && _comps[zplugin]=_zplugin
### End of Zplugin's installer chunk

zstyle ':prezto:*:*' color 'yes'
zstyle ':completion:*' menu select

zplugin ice svn
zplugin snippet PZT::modules/history

# zplugin snippet PZT::modules/syntax-highlighting/init.zsh
# zplugin light zsh-users/zsh-history-substring-search
# zplugin ice svn wait'!0'
# zplugin snippet PZT::modules/history-substring-search
# zplugin ice svn wait'!0' atload'prompt paradox'
# zplugin snippet PZT::modules/prompt
# zplugin ice pick"async.zsh" src"pure.zsh"
# zplugin load "sindresorhus/pure"
zplugin ice src"scripts/base16-gruvbox-dark-medium.sh"
zplugin load "chriskempson/base16-shell"


zplugin ice wait"0" blockf lucid
zplugin light zsh-users/zsh-completions

zplugin ice wait"0" atload"_zsh_autosuggest_start" lucid
zplugin light zsh-users/zsh-autosuggestions

zplugin ice wait"0" atload"bindkey '^[[A' history-substring-search-up; bindkey '^[[B' history-substring-search-down" lucid
zplugin light zsh-users/zsh-history-substring-search


zplugin ice wait"0" atinit"zpcompinit; zpcdreplay" lucid
zplugin light zdharma/fast-syntax-highlighting
# zplugin ice wait'!1'
# zplugin light zdharma/fast-syntax-highlighting

zplugin light denysdovhan/spaceship-prompt

setopt AUTO_CD              # Auto changes to a directory without typing cd.
setopt MULTIOS              # Write to multiple descriptors.
setopt EXTENDED_GLOB        # Use extended globbing syntax.

export USER="wescande"
export MAIL="wescande@student.42.fr"
export EDITOR=vim
export VISUAL=vim

alias gst="git status"
alias glol="git log --graph --pretty='%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
alias glola="git log --graph --pretty='%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --all"

alias ivm="vim"
alias vi="vim"
alias rvim="sudo -E vim"
alias grep="rg"
alias cat="bat"

alias ls="${aliases[ls]:-ls} --group-directories-first"
alias ls="${aliases[ls]:-ls} --color=auto"
alias l='ls -1A'
alias ll='ls -lh'
alias lr='ll -R'
alias la='ll -A'

alias df='df -kh'
alias du='du -kh'

export PATH="${PATH:+${PATH}:}${HOME}/bin:${HOME}/.cargo/bin"
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_COMMAND='(git ls-tree -r --name-only HEAD || rg --files --no-ignore --hidden --follow -g "!{.git,node_modules}/*" )2> /dev/null'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

bindkey "${terminfo[khome]}" beginning-of-line
bindkey "${terminfo[kend]}" end-of-line
bindkey "${terminfo[kdch1]}" delete-char
