### Added by Zplugin's installer
source ~/.zplugin/bin/zplugin.zsh
autoload -Uz _zplugin
(( ${+_comps} )) && _comps[zplugin]=_zplugin
### End of Zplugin's installer chunk

zstyle ':prezto:*:*' color 'yes'
zstyle ':completion:*' menu select
zstyle ':prezto:module:editor' dot-expansion 'yes'
zplugin ice svn
zplugin snippet PZT::modules/history
zplugin ice svn
zplugin snippet PZT::modules/editor

# zplugin snippet PZT::modules/syntax-highlighting/init.zsh
# zplugin light zsh-users/zsh-history-substring-search
# zplugin ice svn wait'!0'
# zplugin snippet PZT::modules/history-substring-search
# zplugin ice svn wait'!0' atload'prompt paradox'
# zplugin snippet PZT::modules/prompt
# zplugin ice pick"async.zsh" src"pure.zsh"
# zplugin load "sindresorhus/pure"
zplugin ice src"scripts/base16-gruvbox-light-medium.sh"
zplugin light "chriskempson/base16-shell"


# zplugin ice wait"0" blockf lucid
# zplugin light zsh-users/zsh-completions

# zplugin ice svn
# zplugin snippet PZT::modules/completion


zplugin ice wait"0" lucid svn blockf \
    atclone'git clone --depth 3 https://github.com/zsh-users/zsh-completions.git external'
zplugin snippet PZT::modules/completion

zplugin ice wait"0" atload"_zsh_autosuggest_start" lucid
zplugin light zsh-users/zsh-autosuggestions

zplugin ice wait"0" atload"bindkey '^[[A' history-substring-search-up; bindkey '^[[B' history-substring-search-down" lucid
zplugin light zsh-users/zsh-history-substring-search


zplugin ice wait"0" atinit"zpcompinit; zpcdreplay" lucid
zplugin light zdharma/fast-syntax-highlighting
# zplugin ice wait'!1'
# zplugin light zdharma/fast-syntax-highlighting


export SPACESHIP_PROMPT_ORDER=(
 # time          # Time stampts section
 user          # Username section
 dir           # Current directory section
 host          # Hostname section
 git           # Git section (git_branch + git_status)
 # hg            # Mercurial section (hg_branch  + hg_status)
 # package       # Package version
 # node          # Node.js section
 # ruby          # Ruby section
 # elm           # Elm section
 # elixir        # Elixir section
 # xcode         # Xcode section
 # swift         # Swift section
 # golang        # Go section
 # php           # PHP section
 # rust          # Rust section
 # haskell       # Haskell Stack section
 # julia         # Julia section
 # docker        # Docker section
 # aws           # Amazon Web Services section
 # venv          # virtualenv section
 # conda         # conda virtualenv section
 # pyenv         # Pyenv section
 # dotnet        # .NET section
 # ember         # Ember.js section
 # kubecontext   # Kubectl context section
 # terraform     # Terraform workspace section
 # exec_time     # Execution time
 line_sep      # Line break
 battery       # Battery level and status
 # vi_mode       # Vi-mode indicator
 jobs          # Background jobs indicator
 # exit_code     # Exit code section
 char          # Prompt character
)
export SPACESHIP_RPROMPT_ORDER=(
 package       # Package version
 rust          # Rust section
 exec_time     # Execution time
 exit_code     # Exit code section
 time          # Time stampts section
)

# SPACESHIP_VI_MODE_SHOW=false
zplugin light denysdovhan/spaceship-prompt

setopt AUTO_CD              # Auto changes to a directory without typing cd.
setopt MULTIOS              # Write to multiple descriptors.
setopt EXTENDED_GLOB        # Use extended globbing syntax.

export USER="william"
export MAIL="wescande@student.42.fr"
export EDITOR=vim
export VISUAL=vim

alias gst="git status"
alias glol="git log --graph --pretty='%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
alias glola="git log --graph --pretty='%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --all"
alias gcam='git commit --all --message'
alias gp='git push'
alias gcf='git commit --amend --reuse-message HEAD'
alias gco='git checkout'
alias gcm='git commit --message'
alias gf='git fetch'
alias gfa='git fetch --all'

alias ivm="vim"
alias vi="vim"
alias rvim="sudo -E vim"
alias grep="rg"
alias cat="bat --theme='Monokai Extended Light'"

alias ls="ls --group-directories-first --color=auto"
alias l='ls -1A'
alias ll='ls -lh'
alias lr='ll -R'
alias la='ll -A'

alias df='df -kh'
alias du='du -kh'
alias open='xdg-open'

export PATH="${PATH:+${PATH}:}${HOME}/bin:${HOME}/.cargo/bin"
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
# export FZF_DEFAULT_COMMAND='(git ls-tree -r --name-only HEAD || rg --files --no-ignore --hidden --follow -g "!{.git,node_modules}/*" )2> /dev/null'
export FZF_DEFAULT_COMMAND='(rg --files --no-ignore --hidden --follow -g "!{.git,node_modules}/*" )2> /dev/null'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
xset r rate 300 40
setxkbmap -option compose:ralt
setxkbmap -option ctrl:nocaps
